eureka:
  client:
    serviceUrl:
      defaultZone: http://andy:passw0rd@localhost:8761/eureka

server:
  port: 9010

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: learning-spring-boot-comment
          group: learning-spring-boot
          content-type: application/json
        output:
          destination: learning-spring-boot-chat
          group: comment-chat
          content-type: application/json
logging:
  level:
    ROOT: debug
